### PR TITLE
Upgrade kernel to 5.4.y LTS

### PR DESCRIPTION
**Pull request by filberg**
This PR upgrades PrawnOS's kernel to version 5.4.23 (LTS) and makes it easy to upgrade to any newer 5.4.yy version.
This guarantees PrawnOS kernel security updates until December 2021, while the current 5.2 kernel is EOL.

### CODE REVIEW

**Comment by SolidHal** [comment]
@filberg This looks great! Thanks! I'll give this a test as soon as I can. @rk-zero could you make sure this doesn't break c100p support when you get a chance?

**Comment by rk-zero** [comment]
Won't boot on neither c100p or c201p. inital ramdisk works, handing over reboots.

**Comment by SolidHal** [comment]
Problem is with how the initramfs gets built. Its pretty brittle right now, copying the needed shared libraries and debian moved some of them around :/ 
building a fixed image now.

**Comment by rk-zero** [comment]
No dice on latest commits, which is sad, because its half commits of the libreboot issue raised.

(please just take the joke, its great work)

**Comment by filberg** [comment]
@rk-zero Thanks for taking the effort to review it :)
It works for me for these use cases:
- "live" from USB
- install on external SD card
- upgrade kernel on existing PrawnOS (5.2.y -> 5.4.23) on internal eMMC

though, I had some issues with the latter (upgrading kernel) because my install had the "legacy" partition layout for FDE (3 partitions, with luks being the 3rd). Turned out I only needed to delete the 2nd partition (mmcblk2p2) to successfully boot with the new initramfs and kernel.

> No dice on latest commits, which is sad, because its half commits of the libreboot issue raised.

Sorry, I don't get it.. could you explain? :) (I'm not  a native English speaker..)

**Comment by SolidHal** [comment]
@rk-zero make sure you build a fresh initramfs with the newest commits. I have encryption functioning on a c201 with commit 9ecc5fe1dfcfaf8f338d48317879f60fe8d2e81d

Without this commit, booting from an encrypted root will always fail due to no fault of this PR. Debian upstream changing library locations caused the initramfs issues.

**Comment by SolidHal** [comment]
@rk-zero you can give https://github.com/SolidHal/PrawnOS/releases/tag/v1.03 a try if you still have issues.

**Comment by rk-zero** [comment]
I compiled fresh, but will try the prebuilt image. I tried booting my compiled image from SD which did not work, but if it works for you, i'll look at my part.

@filberg 333 commits is funny, because SolidHal raised issue 666 in libreboot, where i answered "works for me", which i now listen to.

Thanks again for the great work, always a pleasure to use those devices.

**Comment by rk-zero** [comment]
Works. Left merge conflicts in initramfs-init...

**Comment by SolidHal** [comment]
Great to hear!

**Pull request merged**
