### PR TITLE
Enable LUKS in kernel

### PR DESCRIPTION
**Pull request by JeremyRand**
Based on https://wiki.gentoo.org/wiki/Dm-crypt#Kernel_Configuration

With this PR, ZuluCrypt and ZuluMount work out of the box when installed with apt-get.  (I only tested on Buster.)

Furthermore, with this PR, encrypting the `/home/` directory can be done as follows (assuming that you've already installed ZuluCrypt and ZuluMount with apt-get):

* Log into GUI as normal user.
* Create LUKS container with ZuluCrypt GUI.
* As sudo, move the container to `/luks_home`
* Log out
* Access a console by pressing Ctrl-Alt-F1 (F1 is the Back key)
* Log into console as root
* `zuluMount-cli -m -d /luks_home`
* It will tell you where it's mounted, remember this.  For me, it was `/run/media/private/root/luks_home/`.
* `nano /etc/crypttab`
* Add this line: `luks_home    /luks_home    none    luks`
* Save and exit from nano
* `nano /etc/fstab`
* Add this line: `/dev/mapper/luks_home /home ext4 nodev,nosuid,noatime 0 2`
* Save and exit from nano
* Use `mv` to move all contents of `/home` to the directory where the LUKS container is mounted
* `sync`
* `zuluMount-cli -u -d /luks_home`
* `sync`
* `reboot`

You'll now be asked for your LUKS password during boot.  Note that this will only encrypt the `/home` directory; the rest of the filesystem isn't encrypted.  Also note that I've only tested these instructions once, I take no responsibility if something in these instructions is broken.

### CODE REVIEW

**Comment by JeremyRand** [comment]
Partial credit for the `/home` encryption instructions goes to https://feeding.cloud.geek.nz/posts/encrypting-your-home-directory-using/ and https://askubuntu.com/questions/935311/how-do-i-move-home-folder-to-a-luks-encrypted-external-drive .

**Comment by SolidHal** [comment]
Because of the performance and security benefits of using dmcrypt/LUKS for full root encryption over just encrypting home, also because the internal emmc is very small and determining how big to make a separate /home partition would be difficult without leading to issues I decided to go with full root encryption. 
Thank you for your hard work @JeremyRand but unfortunately, this pull request is no longer needed. 
Of course, if I'm missing something or just flat out wrong please leave a comment and let me know.

**Comment by JeremyRand** [comment]
@SolidHal I'm a bit confused by your comment, as this PR doesn't have anything to do with the distinction between `/home/` encryption and `/` encryption.  I'm pretty sure that the kernel config changes in this PR are needed for both of them.  Whatever additional configuration would be specific to one of those use cases, would presumably be a separate PR.

**Comment by JeremyRand** [comment]
Upon further inspection it looks like all of the kernel config changes in this PR were already merged as part of some other PR that incorporated this one, so indeed, this PR is no longer needed, though not for the reason you stated.  Carry on.  :) 

(And that's super cool that you got `/` encryption working.)

**Comment by SolidHal** [comment]
@JeremyRand Whoops, my mistake. I thought I remembered this PR being about /home encryption for some reason! Sorry for the confusion!

**Pull request closed without merging**
