### PR TITLE
initial shellcheck tests

### PR DESCRIPTION
**Pull request by austin987**
I started on this a while back, but got sidetracked (and wanted to fix outstanding issues first).

However, since https://github.com/SolidHal/PrawnOS/commit/0bd5575b0b84bcf469cd0b94351c10f1a0a459f9 broke install for me, and would easily have been caught by shellcheck, I revisited it.

This is an initial pass. It currently ignores SC2068 (unquoted variables), and style issues in favor of only flagging error level issues.

To get that level of checking, however, I had to fix some outstanding issues, first ;).

@SolidHal

### CODE REVIEW

**Comment by austin987** [comment]
Marking WIP while I look closer at something.

**Comment by austin987** [comment]
Removing WIP, the issue I was seeing was unrelated to this.

This can go in.

**Comment by SolidHal** [comment]
fixed up the conflicts, will merge when checks pass

**Review by SolidHal — APPROVED** [review]

**Comment by SolidHal** [comment]
Merged this in 05746fcbb092715d48fc1cc9af4963341eaac8dd

**Pull request closed without merging**
