### PR TITLE
misc shellcheck fixes

### PR DESCRIPTION
**Pull request by austin987**

### CODE REVIEW

**Comment by SolidHal** [comment]
Overall this looks like a nice cleanup. I especially like the inclusion of the "-r" on read, helps avoid any "weirdness" if someone enters a backslash.

**Comment by austin987** [comment]
Rebased after 93192fa5117adb15e456c856d27bac911877a435

**Comment by austin987** [comment]
Rebased. @SolidHal can this be merged please? :)

**Comment by SolidHal** [comment]
Thanks for addressing my comment and rebasing, merging this

**Pull request merged**
