### PR TITLE
Add documentation on enabling developer mode

### PR DESCRIPTION
**Pull request by austin987**

### CODE REVIEW

**Comment by gdallasdye** [comment]
Some thoughts: I'm not sure it would be advisable to encourage the user to agree to the vendor's terms while network connected? 

Starting at and with Screen Eight, could you document the process of enabling developer mode by switching to the tty terminal? By Screen Seven, you can do the usual ctrl+alt+f2, and I think you can skip the sudo -i and run those crossystem commands with sudo appended. It's been a while since I tested that however...

**Comment by austin987** [comment]
Ah nice, didn't know that you could use the vtty there, that makes things much easier!

I've updated accordingly, we log in as root, so sudo isn't needed at all. I also used F3 instead, so it's consistent with the original command (and I feel like describing F2 as right arrow might be confusing..).

**Comment by SolidHal** [comment]
Thanks @austin987 for documenting this, and thanks @gdallasdye for that trick. 

To avoid confusion with the F-keys and their labels, we could say `F3 (aka Browser Refresh Key), etc

I think this makes sense to include in `DOCUMENTATION.md` rather than as its own standalone file to avoid cluttering the root.

**Comment by austin987** [comment]
@SolidHal updated to put the instructions in README.md instead.

I've left the keys as they were originally. I'm not opposed to changing it, but (IMO) `F3 (aka Browser Refresh Key)` is more confusing than `'REFRESH' (F3)`. If you feel strongly, I can change that of course, but maybe let's explore other wordings first :).

**Comment by SolidHal** [comment]
>I've left the keys as they were originally. I'm not opposed to changing it, but (IMO) F3 (aka Browser Refresh Key) is more confusing than 'REFRESH' (F3). If you feel strongly, I can change that of course, but maybe let's explore other wordings first :).

Fine by me! Thanks again for writing this up. I agree that the README is probably a find location for this for now :)

**Pull request merged**
