### PR TITLE
Support suites other than Stretch

### PR DESCRIPTION
**Pull request by JeremyRand**
Tested with Stretch and Buster; there's some untested support for Sid as well, which might need further tweaks.

### CODE REVIEW

**Comment by JeremyRand** [comment]
It looks like there are some merge conflicts due to changes made in PrawnOS since this PR was branched a few days ago; I'll rebase shortly.

**Comment by JeremyRand** [comment]
Fixed the merge conflict.  I haven't yet tested this PR after the rebase; I'll do so as soon as I can (but anyone else is welcome to help test it too).

**Comment by JeremyRand** [comment]
Tested after the rebase, and also fixed (and tested) Sid.  So, AFAICT this is ready to consider for merging.

**Comment by SolidHal** [comment]
I'll give this a test soon. Is there a reason you chose to use "PRAWNOS_SUITE" instead of something like "DEBIAN_VERSION" since that is what majorly changes when you specify "sid" or "buster"?

**Comment by SolidHal** [comment]
Just got a chance to test this out, buster seems to work perfectly! 
After testing, I feel more alright with transferring to buster and ditching stretch as the "official" version, especially since it looks like you've been testing encryption on buster. 

I know I said that buster wasn't a goal for the first non-alpha release, but since it simplifies the number of debian repos we need to build from, seems to be just as stable as stretch at this point, and has newer software I'm definitely rethinking that. 

The only major change I would like made is instead of "PRAWNOS_SUITE" maybe "DEBIAN_VERSION" or "DEBIAN_RELEASE". Which do you feel is more appropriate? I feel like "PRAWNOS_SUITE" isn't very descriptive of what is changing. 

Oh, and if you want any changes to your list of contributions in the AUTHORS file, feel free to add those to this request as well. 

Otherwise I'm happy to merge this.

**Comment by JeremyRand** [comment]
> Is there a reason you chose to use "PRAWNOS_SUITE" instead of something like "DEBIAN_VERSION" since that is what majorly changes when you specify "sid" or "buster"?

@SolidHal The `debootstrap` manpage refers to things like `stretch` and `buster` as "suites" rather than "versions", so I used that term for consistency.  I used the prefix `PRAWNOS_` rather than `DEBIAN_` to avoid potential namespace conflicts with other software.  (For example, it is plausible that Debian might choose to set an env variable `DEBIAN_SUITE` to refer to the currently installed suite, which wouldn't be what we want here.  Using `PRAWNOS_` as the prefix should avoid the risk of such conflicts.)

**Comment by SolidHal** [comment]
@JeremyRand That all seems reasonable then, thanks for the explanation. Thanks for your work on this.

**Pull request merged**
