### PR TITLE
Detect encrypted volumes using blkid instead of another partition

### PR DESCRIPTION
**Pull request by tslilc**
This is the (essentially) the setup that i'm using. It was a little irritating that the new version wasn't backwards compatible -- a valuable part of PrawnOS is the kernel, and we might consider making that usable outside of the particulars of this setup.

Is there a compelling reason for a separate partition?

(I haven't checked the build scripts, but the initramfs and partition map is what i'm using and it seems to work)

### CODE REVIEW

**Comment by tslilc** [comment]
Oh, sorry, these were meant to be two different pull requests. I'm not entirely sure how to split them out.

**Comment by SolidHal** [comment]
### Regarding the crypto blkid change

@tslilc I really like the idea of detecting crypto based on the partition. I didn't know we could do it with blkid. 

> Is there a compelling reason for a separate partition?

I added the separate /boot partition when I thought we could load the initramfs from it, making everything more flexible. But, since we have to build the initramfs into the kernel, we are stuck with some in-flexibility. Only reason to keep it around is for easier debugging of the initramfs, but I don't think that is compelling enough. I can think of another way to facilitate that, maybe by detecting a specifically formatted USB device. Just an off-the-cuff idea. 

> It was a little irritating that the new version wasn't backwards compatible

Unfortunately it is bound to happen some times, PrawnOS is still in Alpha by my standards and is likely to break backwards compatibility again before we have something that I would consider "stable".

> a valuable part of PrawnOS is the kernel, and we might consider making that usable outside of the particulars of this setup.

The goal of PrawnOS is to be a libre linux kernel and filesystem for the c201. If others want to use the kernel PrawnOS provides, I'm happy to supply help and listen to feedback but I can't be confident in saying that it'll always be easy to separate the kernel from the filesystem. That said, I don't foresee adding any features that would make the separation any harder. 

I'll test this out and merge it, this makes a lot more sense than the current setup. Thanks!

### Regarding verifying the kernel
This is really something we should have been doing from the beginning, but honestly I forgot about it. 
What does the user see/what does the script do when the verification fails? 
What does the user see/what does the script do when the verification succeeds?
I'd like to make it clear to the user what the verification means, and how to proceed if failure occurs. 
Of course, I can handle all of that if you don't want to :)

**Comment by rk-zero** [comment]
Won't boot as of now and debugging the initramfs is out of my knowledge without a /boot partition.

Maybe not such a bad idea after all?! ...

**Comment by SolidHal** [comment]
With this PR @rk-zero, or with master? 

There’s definitely some script changes that I’ll need to make in addition to this, so I wouldn’t be surprised if this PR doesn’t work straight away.

**Comment by rk-zero** [comment]
Well, i use my own fork, but applied your commits to mine and made the fixes in the comments.
I still try to trigger the rescue shell through a special partition label, like:
cgpt add -i 1 -l "RESCUE" /dev/sda1
but it just reboots the system.
Older releases work fine. I still think this is the way to go for future releases.

Another thing that makes me twitch is the dumb copy of a partition table. You can boot the book from emmc just fine by partitioning by hand, even with both gpt tables intact. Using the same uuids over and over again seems counter-intuitive when you use it to find the rootpartition.

As i have no idea about initramfs, i will learn that route now, update my fork and get back to this then.

**Comment by rk-zero** [comment]
Oh, i didn't see you replied, not tslilc.

please see my current initramfs-init https://github.com/rk-zero/PrawnOS/commit/f2acfa469e0d67c7aab4b1538072a42a07675e03, i went with your suggestion to use a special usb-drive and labeled some partitions with a "RESCUE" name. My other 5.3.1 and your 5.2.9 kernels boot fine, this is the only modification i merged and it just scrolls REALLY fast, then reboots.

I tried to trigger the rescue shell with:

if [ -n "$(blkid | grep RESCUESHELL)" ]
then
    rescue_shell debug
fi

but that didn't work. I still learn about your build process, so i can play with kernel and initramfs without having to recompile from scratch every time

**Comment by SolidHal** [comment]
Merged into dev branch so I can test and fixup, feel free to still comment here as I'll watch it until its merged into master

**Comment by rk-zero** [comment]
#mount the initramfs partition 
mount -o noatime ${outdev}p3 $outmnt/boot

This was the problematic line. In buildFilesystem we don't add a boot partition, so root is p2, not p3 anymore. Mount will fail and the initramfs won't be copied at all. Just comment it out and use the /boot on the root partition, it will get deleted later anyway.

So my issue was, that the kernel was booting, not finding the initramfs and paniced.

Finally understood the build system enough to just rebuild the initramfs, inject it and inject the kernel into a new image without recompiling everything.

Lots of research went into this as i can see, kudos.

**Comment by rk-zero** [comment]
Well, it boots now and even drops to rescue_shell with the RESCUESHELL partition label.

please see my changes in:

https://github.com/rk-zero/PrawnOS/commit/809e0166369859d3f2b4dd3498c4c7d145a3e235
https://github.com/rk-zero/PrawnOS/commit/f2acfa469e0d67c7aab4b1538072a42a07675e03
https://github.com/rk-zero/PrawnOS/commit/4ebc27457c9b76cf5b0b0fb15dbeb014d8562e47
https://github.com/rk-zero/PrawnOS/commit/f9a1cc42a8e44a4ee23290c985a01fa709a9536f
https://github.com/rk-zero/PrawnOS/commit/f26cabf531cf4ae52fb07f2e6f932a8dd4bbec0b

I know that is a lot, so you can simply diff /scripts and the makefile which should cover all the necessary changes.

Still cannot believe it actually works, though.

**Pull request merged**
