### PR TITLE
Added support for "scarlet" (Acer Chromebook Tab 10)

### PR DESCRIPTION
**Pull request by colemancda**
Added support for Acer Chromebook Tab 10 (scarlet), another RK3399 / OP1 (gru) Chromebook device.

### CODE REVIEW

**Comment by SolidHal** [comment]
This looks great! I wasn't even aware of gru-scarlet. How does xfce4 or gnome run on it? 
I see two device trees are added, `inx` and `kd`. Do you happen to know the difference between them?

**Comment by colemancda** [comment]
The variation is because of the different display vendor (Innolux, Kingdisplay)
https://github.com/torvalds/linux/commit/505a2fd80b4dcd9e89bcf426ba4314ea339911e8

**Comment by colemancda** [comment]
TBH I haven't been able to make any builds yet, I actually don't have a x86 Linux PC at my disposal and am trying to build the image on a Pi 4 (Buster)

**Comment by SolidHal** [comment]
Post whatever troubles you run in to building on an arm device, it is something I would like to work to support.

**Comment by rk-zero** [comment]
I like the fixes to CI/CD but this looks like a very old fork. Can we get a hint on what is needed for scarlet other then dts?

**Comment by spoelstraethan** [comment]
I have one of these on the way so I'm hoping to provide some additional testing soon as well.

**Comment by spoelstraethan** [comment]
> I have one of these on the way so I'm hoping to provide some additional testing soon as well.

With the latest image from this pull request's pipeline (as well as the last main release) I'm just getting a black/blank screen after selecting the USB/SD card option.

**Comment by colemancda** [comment]
I am getting the same. I was not able to get it to work on the tablet either.

**Comment by Maccraft123** [comment]
@colemancda is panel driver enabled on kconfig? can you ssh into machine?

**Comment by spoelstraethan** [comment]
I'm hoping to play with this a little more this weekend with a USB-C dock and a wired network connection (if SSH is enabled by default on boot, otherwise I can always probably do that via the chroot before rebooting), but I tested with ArchLinuxARM (and there isn't an official page for this device there either, just the C101P which happens to share the same chipset) and I  got the same "gray" screen where the system doesn't appear to be properly transitioning from the bootloader (which is an interesting menu on the tablet only models).

**Pull request closed without merging**
