### PR TITLE
Update kernel to latest 5.4.29 + add CIFS support

### PR DESCRIPTION
**Pull request by filberg**
This PR updates kernel config and build script to track the latest (at the time of creating this PR) upstream linux-libre kernel.

This also adds support for CIFS module into the kernel.

The CIFS commit was tested with a freshly built image on a c201p, installed on internal eMMC.
The kernel commit was tested upon the image previously built for CIFS, using UpgradeKernel.sh script to inject the new kernel.

### CODE REVIEW

**Comment by rk-zero** [comment]
Does your Prawn still compile without errors? I had to manually compile ath9k to make it work.

**Comment by filberg** [comment]
> Does your Prawn still compile without errors? I had to manually compile ath9k to make it work.

@rk-zero  you're right..

`make image` 

now fails at 

`mkimage -D '-I dts -O dtb -p 2048' -f kernel.its vmlinux.uimg` 

with 

`FATAL ERROR: Couldn't open "arch/arm/boot/zImage": No such file or directory
mkimage: Can't open vmlinux.uimg.tmp: No such file or directory`

Though, kernel compiles just fine with

`make clean_kernel`
`make kernel`

**Comment by rk-zero** [comment]
Yes, i got it working with
make toolchain
make firmware
in the build ath9k directory.
You may also need texinfo deb package.

**Comment by gdallasdye** [comment]
Quick question: What arch are you guys compiling on? I'm building on my dev sdcard on the C201, and I also fail the ath9k stage too. 

I'll install the texinfo package and try again. If the documentation needs to be updated to include that package, I believe it also may be worth mentioning that PrawnOS can also build itself, not just a Debian 10 VM. Tested a couple dozen times.

**Comment by rk-zero** [comment]
Yes, i also build directly on a c201p or c100p - works flawless.
make toolchain in ath9k complains about missing makeinfo, which is included there.

**Comment by filberg** [comment]
>  I believe it also may be worth mentioning that PrawnOS can also build itself, not just a Debian 10 VM. Tested a couple dozen times.

That's great. This is also a plus to possibly enforce GNU-FSDG in the future..
Too bad PureOS only targets amd64 and aarch64, otherwise rebasing on it would make FSGD compliance fairly easy.. and RYF too..

**Comment by SolidHal** [comment]
@filberg 
> > Does your Prawn still compile without errors? I had to manually compile ath9k to make it work.
> 
> @rk-zero you're right..
> 
> `make image`
> 
> now fails at
> 
> `mkimage -D '-I dts -O dtb -p 2048' -f kernel.its vmlinux.uimg`
> 
> with
> 
> `FATAL ERROR: Couldn't open "arch/arm/boot/zImage": No such file or directory mkimage: Can't open vmlinux.uimg.tmp: No such file or directory`
> 
> Though, kernel compiles just fine with
> 
> `make clean_kernel`
> `make kernel`

Probably had something weird and stale in your linux build dir

@rk-zero 
> Does your Prawn still compile without errors? I had to manually compile ath9k to make it work.
I'll wipe my buid dir and see if I can reproduce

**Comment by SolidHal** [comment]
@rk-zero @filberg 
Getting building on a c201 supported should be easy enough.  @rk-zero do you change anything to build on the c201? 

> That's great. This is also a plus to possibly enforce GNU-FSDG in the future..
> Too bad PureOS only targets amd64 and aarch64, otherwise rebasing on it would make FSGD compliance fairly easy.. and RYF too..

Definitely interested in achieving compliance with RYF and FSGD. Will have to look into the requirements.

**Comment by gdallasdye** [comment]
>  @gdallasdye do you change anything to build on the c201?

Nope. I just follow the sudo apt install dependencies (now with texinfo) to set up a fresh Debian 10 to build PrawnOS. 

FWIW, When git cloning, I clone into two folders, one with @SolidHal's and the other mine. I copy paste my changes to my folder, build vanilla and then build mine. Then testing happens on emmc and usb installs while the dev sdcard is safely detached.

**Comment by rk-zero** [comment]
Solids repo builds fine, so i guess our build errors are due to a different kernel config.

**Comment by gdallasdye** [comment]
@filberg @rk-zero Both your repos build (run, install, install gui) fine for me. You may want to "sudo rm -rf build" before trying again. It's not the kernel config that's causing problems.

**Comment by filberg** [comment]
@SolidHal 
>Probably had something weird and stale in your linux build dir

Yes, must have been the case.
Also, worth noting that installing `texinfo` seems to guarantee a clean build to succeed.
It's now building flawlessly.

@rk-zero 
> Solids repo builds fine, so i guess our build errors are due to a different kernel config.

The only difference in config shuold be `CONFIG_CIFS=y`

Is it possible that enabling CIFS introduced dependency on texinfo?
I think the culprit here is the lack of `texinfo` in the build environment. At least it was in my case.

**Pull request merged**
